-- Email verification and self-service password reset.
--
-- Both flows are the same shape — mail the user a high-entropy secret, let them
-- present it back once — so they share one table keyed by `purpose` rather than
-- duplicating the machinery twice.
--
-- WHY ONLY A HASH IS STORED: these tokens are password-equivalent. A reset token
-- IS the ability to take over the account, so storing raw tokens would turn any
-- read of this table (a leaked backup, a SQL injection, an over-broad support
-- query) into account takeover for every pending reset. Storing SHA-256 means a
-- stolen table is inert: the lookup hashes the presented token and compares.
--
-- SHA-256 rather than BCrypt, which is right here and wrong for passwords: the
-- token is 256 bits from a CSPRNG, so there is no dictionary to grind and
-- nothing for a slow KDF to buy. Passwords are low-entropy and human-chosen,
-- which is exactly when BCrypt's cost matters — see users.password_hash.

ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP(6);

-- Accounts that predate verification are grandfathered in. They registered when
-- no verification existed, so treating them as unverified would retroactively
-- flag every existing user — including the seeded officers.
UPDATE users SET email_verified_at = created_at;

CREATE TABLE auth_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SHA-256 of the emailed token, hex. The token itself is never stored.
    token_hash  VARCHAR(64) NOT NULL,
    -- EMAIL_VERIFICATION | PASSWORD_RESET
    purpose     VARCHAR(24) NOT NULL,
    user_id     BIGINT NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    -- Set the moment it is redeemed; single-use is enforced on this column.
    consumed_at TIMESTAMP(6),
    CONSTRAINT uq_auth_tokens_hash UNIQUE (token_hash),
    -- Disposable per-request state, like refresh_tokens: cascade rather than
    -- keep orphans pointing at a deleted account.
    CONSTRAINT fk_auth_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Issuing a new token invalidates the user's outstanding ones of that purpose,
-- so the common write path filters on exactly this pair.
CREATE INDEX idx_auth_tokens_user_purpose ON auth_tokens (user_id, purpose);
-- The hourly cleanup job deletes by expiry.
CREATE INDEX idx_auth_tokens_expires_at ON auth_tokens (expires_at);
