-- Canonical category registry.
--
-- Until now `category` was a free-form VARCHAR written by whoever was calling:
-- the submit form's own hardcoded vocabulary, and whatever an API client sent.
-- Nothing stopped 'garbage', 'Garbage', 'Solid Waste' and 'uncollected garbage'
-- from coexisting, and every consumer treats category as an EXACT-equality key
-- -- the semantic matcher's candidate pre-filter (ward + category + status),
-- the naive fallback, the dashboard breakdown. Four spellings of one problem
-- therefore mean four incidents that never merge and four dashboard rows.
--
-- The fix is a registry with aliases, not fuzzy matching at query time:
-- normalise once on the way in, then keep comparing exact canonical codes. The
-- matching SQL in backend-node is untouched by this migration, by design.
--
-- `code` is the canonical identifier and stays the value stored in
-- complaints.category / incidents.category, so existing rows, indexes and the
-- Node matcher keep working unchanged. The raw string the caller sent is
-- preserved alongside it in `source_category` for audit and debugging.

CREATE TABLE categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable, lowercase, never renamed. This is what lands in
    -- complaints.category and what every filter compares against.
    code         VARCHAR(64)  NOT NULL,
    -- Officer-facing canonical name.
    name         VARCHAR(255) NOT NULL,
    -- Resident-facing label on the submit form. Separate from `name` because
    -- the two audiences genuinely want different words for the same thing.
    display_name VARCHAR(255) NOT NULL,
    -- Retired categories stay readable (old complaints still reference them)
    -- but drop out of the submit form and stop being accepted on new reports.
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Optional rollup, e.g. a future 'pothole' under 'roads'. Unused at seed
    -- time; present so introducing a hierarchy later is not another migration
    -- of every consumer.
    parent_id    BIGINT,
    -- Submit-form ordering. 'other' sorts last deliberately.
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_categories_code UNIQUE (code),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

-- Every accepted spelling of a category, stored ALREADY NORMALISED: lowercased,
-- with each run of non-alphanumeric characters collapsed to one space, trimmed.
-- CategoryNormalizer.normalise() in backend-spring applies the identical
-- transform to incoming values, so resolution is a plain equality hit on this
-- table and never a LIKE or a similarity search.
--
-- Canonical codes are themselves seeded as aliases, so resolution is one query.
CREATE TABLE category_aliases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL,
    alias       VARCHAR(128) NOT NULL,
    -- Which vocabulary this spelling came from. 'internal' is our own UI and
    -- API surface; an external feed gets its own source row so a term that
    -- means something different over there cannot hijack our vocabulary.
    source      VARCHAR(64)  NOT NULL DEFAULT 'internal',
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_category_aliases_source_alias UNIQUE (source, alias),
    CONSTRAINT fk_category_aliases_category
        FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_category_aliases_alias ON category_aliases (alias);

-- The vocabulary the submit form already shipped, promoted to canonical so that
-- no existing complaint changes category as a result of this migration.
INSERT INTO categories (code, name, display_name, sort_order, created_at, updated_at) VALUES
    ('pothole',     'Pothole / road damage', 'Pothole or damaged road',       10, NOW(), NOW()),
    ('streetlight', 'Street lighting',       'Street light out',              20, NOW(), NOW()),
    ('garbage',     'Solid waste',           'Garbage not collected',         30, NOW(), NOW()),
    ('water',       'Water supply',          'Water supply or leak',          40, NOW(), NOW()),
    ('drainage',    'Drainage',              'Blocked drain or waterlogging', 50, NOW(), NOW()),
    ('other',       'Other',                 'Something else',                99, NOW(), NOW());

-- Aliases: the spellings a resident, an officer, or an external feed plausibly
-- uses for the same problem. These cover the exact collisions the audit
-- recorded -- 'Road Damage' vs 'Pothole', 'Garbage' vs 'Solid Waste',
-- 'Street Light' vs 'Streetlight', 'Drainage' vs 'Blocked Drain'.
--
-- Note what is deliberately NOT here: no alias maps to a category it merely
-- resembles. 'sewage' is drainage, but it is not water, because a water-supply
-- failure and a sewage overflow belong to different departments and merging
-- them would be a worse bug than the fragmentation this table fixes.
INSERT INTO category_aliases (category_id, alias, source, created_at)
SELECT c.id, a.alias, 'internal', NOW()
FROM categories c
JOIN (VALUES
    ('pothole',     'pothole'),
    ('pothole',     'potholes'),
    ('pothole',     'road damage'),
    ('pothole',     'damaged road'),
    ('pothole',     'broken road'),
    ('pothole',     'bad road'),
    ('pothole',     'road repair'),
    ('pothole',     'road'),
    ('pothole',     'roads'),
    ('streetlight', 'streetlight'),
    ('streetlight', 'streetlights'),
    ('streetlight', 'street light'),
    ('streetlight', 'street lights'),
    ('streetlight', 'street lighting'),
    ('streetlight', 'street lamp'),
    ('streetlight', 'light not working'),
    ('streetlight', 'lighting'),
    ('garbage',     'garbage'),
    ('garbage',     'garbage not collected'),
    ('garbage',     'uncollected garbage'),
    ('garbage',     'solid waste'),
    ('garbage',     'waste'),
    ('garbage',     'trash'),
    ('garbage',     'rubbish'),
    ('garbage',     'litter'),
    ('garbage',     'refuse'),
    ('garbage',     'sanitation'),
    ('water',       'water'),
    ('water',       'water supply'),
    ('water',       'water leak'),
    ('water',       'leak'),
    ('water',       'leakage'),
    ('water',       'pipeline leak'),
    ('water',       'burst pipe'),
    ('water',       'no water'),
    ('water',       'water shortage'),
    ('drainage',    'drainage'),
    ('drainage',    'drain'),
    ('drainage',    'blocked drain'),
    ('drainage',    'open drain'),
    ('drainage',    'sewage'),
    ('drainage',    'sewer'),
    ('drainage',    'waterlogging'),
    ('drainage',    'water logging'),
    ('drainage',    'storm water'),
    ('other',       'other'),
    ('other',       'others'),
    ('other',       'miscellaneous'),
    ('other',       'general'),
    ('other',       'something else')
) AS a(code, alias) ON a.code = c.code;

-- The raw string the caller sent, kept so a normalisation decision is always
-- reversible and auditable. NULL on rows created before this migration, where
-- the stored value WAS the raw value.
ALTER TABLE complaints ADD COLUMN source_category VARCHAR(255);
ALTER TABLE incidents  ADD COLUMN source_category VARCHAR(255);

-- Backfill: fold existing rows onto canonical codes wherever an alias resolves
-- them, preserving what was there first.
--
-- Rows that resolve to NOTHING are deliberately LEFT ALONE rather than swept
-- into 'other'. Forcing an unrecognised value into 'other' would merge
-- genuinely unrelated complaints into one candidate pool -- a worse fault than
-- the fragmentation this migration exists to fix -- and it would do so
-- irreversibly for anyone reading `category` alone. Leaving them is simply the
-- status quo: they keep grouping only with their own spelling.
--
-- To find what was left behind (the quarantine report):
--   SELECT category, COUNT(*) FROM complaints
--   WHERE category NOT IN (SELECT code FROM categories)
--   GROUP BY category ORDER BY 2 DESC;
UPDATE complaints c
SET source_category = c.category,
    category        = cat.code
FROM category_aliases a
JOIN categories cat ON cat.id = a.category_id
WHERE a.source = 'internal'
  AND a.alias = btrim(regexp_replace(lower(c.category), '[^a-z0-9]+', ' ', 'g'))
  AND c.category <> cat.code;

UPDATE incidents i
SET source_category = i.category,
    category        = cat.code
FROM category_aliases a
JOIN categories cat ON cat.id = a.category_id
WHERE a.source = 'internal'
  AND a.alias = btrim(regexp_replace(lower(i.category), '[^a-z0-9]+', ' ', 'g'))
  AND i.category <> cat.code;
