-- The ingestion boundary for externally-sourced complaints.
--
-- Everything the platform knows today arrived through POST /complaints, which
-- validates as it writes. An external feed cannot use that path: it arrives in
-- bulk, in somebody else's vocabulary, with its own identifiers, and — the part
-- that matters — it arrives AGAIN tomorrow with yesterday's rows in it.
--
-- Without a boundary, bad external data does not fail loudly. It lands in
-- `complaints` and silently contaminates matching (ward and category are exact
-- pre-filters), the dashboard, and every priority score derived from them. By
-- the time anyone notices, there is no record of what arrived or what was
-- changed on the way in.
--
-- So: raw first, decide second, write third. Every record that arrives is
-- stored VERBATIM before anything looks at it, every rejection carries its
-- reasons, and re-running the same input changes nothing.

-- Where a complaint came from, when it did not come from a person on the site.
-- NULL for everything submitted through the public form, which is the default
-- and stays the common case.
ALTER TABLE complaints
    ADD COLUMN source           VARCHAR(64),
    -- The feed's own identifier for this report. Kept because it is the only
    -- stable handle back to the upstream record — ours is an identity we
    -- invented and the source has never heard of.
    ADD COLUMN source_record_id VARCHAR(128);

-- Identity within a feed. Partial, so the millions of ordinary complaints with
-- no source cost nothing and are not forced to be unique on NULL.
CREATE UNIQUE INDEX uq_complaints_source_record
    ON complaints (source, source_record_id)
    WHERE source IS NOT NULL AND source_record_id IS NOT NULL;

-- One run of one feed.
CREATE TABLE ingestion_batches (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(64)  NOT NULL,
    started_at   TIMESTAMP(6) NOT NULL,
    finished_at  TIMESTAMP(6),
    -- The metrics the audit asks to be visible. Counted from the record rows
    -- rather than incremented in flight, so a crashed run cannot leave a lie
    -- behind.
    received     INTEGER      NOT NULL DEFAULT 0,
    accepted     INTEGER      NOT NULL DEFAULT 0,
    rejected     INTEGER      NOT NULL DEFAULT 0,
    duplicates   INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_ingestion_batches_source ON ingestion_batches (source, started_at DESC);

-- Every record that arrived, accepted or not.
--
-- THE RAW PAYLOAD IS STORED BEFORE VALIDATION, not after. A record rejected for
-- a malformed coordinate is exactly the record someone will need to look at to
-- find out what the feed is doing wrong, and a gate that discards what it
-- refuses gives you a count and no way to act on it.
CREATE TABLE ingestion_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         BIGINT       NOT NULL,
    source           VARCHAR(64)  NOT NULL,
    -- NULL when the feed sent no identifier at all — itself a rejection reason,
    -- because without one no run can be idempotent.
    source_record_id VARCHAR(128),
    raw              JSONB        NOT NULL,
    -- Hash of the raw payload. What makes a re-run cheap AND lets an UPDATED
    -- record be told from an unchanged one.
    content_hash     VARCHAR(64)  NOT NULL,
    -- ACCEPTED | UPDATED | UNCHANGED | DUPLICATE | REJECTED
    status           VARCHAR(16)  NOT NULL,
    -- Every rejected record has a reason, in the record, in machine-readable
    -- form. A log line is not a reason: it is not queryable, and it is gone.
    rejection_reasons JSONB       NOT NULL DEFAULT '[]'::jsonb,
    -- What it became, when it was accepted.
    complaint_id     BIGINT,
    created_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_ingestion_records_batch
        FOREIGN KEY (batch_id) REFERENCES ingestion_batches (id),
    CONSTRAINT fk_ingestion_records_complaint
        FOREIGN KEY (complaint_id) REFERENCES complaints (id)
);

CREATE INDEX idx_ingestion_records_batch  ON ingestion_records (batch_id);
CREATE INDEX idx_ingestion_records_status ON ingestion_records (source, status, created_at DESC);
CREATE INDEX idx_ingestion_records_source_id
    ON ingestion_records (source, source_record_id);

-- The rejection report, as a view so it cannot go stale.
--
-- This is the thing an operator actually opens: what is this feed getting
-- wrong, how often, and show me an example I can take upstream.
CREATE VIEW ingestion_rejections AS
SELECT r.source,
       reason.value ->> 'field'                     AS field,
       reason.value ->> 'code'                      AS code,
       COUNT(*)                                     AS occurrences,
       MAX(r.created_at)                            AS last_seen,
       (ARRAY_AGG(r.source_record_id ORDER BY r.created_at DESC))[1] AS example_record_id,
       (ARRAY_AGG(r.raw             ORDER BY r.created_at DESC))[1]  AS example_payload
FROM ingestion_records r
CROSS JOIN LATERAL jsonb_array_elements(r.rejection_reasons) AS reason(value)
WHERE r.status = 'REJECTED'
GROUP BY r.source, reason.value ->> 'field', reason.value ->> 'code';

COMMENT ON VIEW ingestion_rejections IS
    'What an external feed is getting wrong, grouped by field and reason, with '
    'a sample payload to take back to whoever publishes it.';
