-- CivicPulse core schema (Phase 0).
--
-- backend-spring owns migrations for ALL shared tables — including the ones
-- backend-node reads and writes. See docs/service-boundaries.md decision 3.
-- backend-node never runs DDL; when it needs a column (e.g. the Phase 2
-- pgvector embedding), that migration is added here.
--
-- Entities in src/main/java/.../entity must stay in sync: Hibernate runs
-- with ddl-auto=validate and fails startup on drift.

-- pgvector, needed from Phase 2 for semantic incident matching. Created
-- here rather than out-of-band so a brand-new database (a fresh Neon
-- branch, for instance) is fully provisioned by the migrations alone.
-- Requires a role that may create extensions — Neon's default owner can.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE wards (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    zone       VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE departments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- Incidents are the unit officers act on: a group of semantically related
-- complaints, carrying a priority score AND the human-readable reasons for
-- it (explainability is a core project claim, not a nice-to-have).
CREATE TABLE incidents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id           BIGINT NOT NULL,
    department_id     BIGINT,
    title             VARCHAR(255),
    summary           TEXT,
    category          VARCHAR(255) NOT NULL,
    priority_score    DOUBLE PRECISION NOT NULL DEFAULT 0,
    priority_reasons  JSONB NOT NULL DEFAULT '[]'::jsonb,
    status            VARCHAR(255) NOT NULL,
    complaint_count   INTEGER NOT NULL DEFAULT 1,
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    ai_recommendation TEXT,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_incidents_ward FOREIGN KEY (ward_id) REFERENCES wards (id),
    CONSTRAINT fk_incidents_department FOREIGN KEY (department_id) REFERENCES departments (id)
);

-- Supports backend-node's Phase 2 candidate pre-filter, which narrows by
-- ward + category + status BEFORE running any vector similarity comparison.
CREATE INDEX idx_incidents_matching ON incidents (ward_id, category, status);
CREATE INDEX idx_incidents_status ON incidents (status);
CREATE INDEX idx_incidents_priority_score ON incidents (priority_score);

-- user_id is nullable on purpose: complaint submission is open/anonymous
-- (see docs/endpoints.md). Only *tracking* your own complaints requires an
-- account.
CREATE TABLE complaints (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    ward_id       BIGINT NOT NULL,
    incident_id   BIGINT,
    department_id BIGINT,
    title         VARCHAR(255),
    description   TEXT NOT NULL,
    category      VARCHAR(255) NOT NULL,
    latitude      DOUBLE PRECISION NOT NULL,
    longitude     DOUBLE PRECISION NOT NULL,
    status        VARCHAR(255) NOT NULL,
    photo_url     VARCHAR(1024),
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_complaints_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_complaints_ward FOREIGN KEY (ward_id) REFERENCES wards (id),
    CONSTRAINT fk_complaints_incident FOREIGN KEY (incident_id) REFERENCES incidents (id),
    CONSTRAINT fk_complaints_department FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE INDEX idx_complaints_ward_id ON complaints (ward_id);
CREATE INDEX idx_complaints_incident_id ON complaints (incident_id);
CREATE INDEX idx_complaints_user_id ON complaints (user_id);
CREATE INDEX idx_complaints_status ON complaints (status);
CREATE INDEX idx_complaints_created_at ON complaints (created_at);

-- Phase 2 will add the complaint embedding column as a new V*__ migration:
--   ALTER TABLE complaints ADD COLUMN embedding vector(<dim>);
-- once the embedding provider — and therefore the dimension — is chosen.
-- The extension itself is already enabled at the top of this file.
