-- Phase 2: embeddings + semantic incident matching.
--
-- backend-node becomes the real matcher. It generates a complaint embedding
-- (Gemini gemini-embedding-001, 1536-dim, L2-normalised), compares it against
-- candidate incidents with pgvector, and asks Spring to attach the complaint.
-- Spring stays the single writer of incident membership; see
-- docs/service-boundaries.md decision 2.
--
-- Column ownership (also in service-boundaries.md):
--   embedding                       — written by backend-node ONLY (parameterised
--                                     UPDATE ... $1::vector; never interpolated).
--   matching_status PENDING<->PROCESSING — backend-node (atomic CAS claim).
--   matching_status MATCHED / DEGRADED   — backend-spring only (terminal).
--
-- The `vector` extension itself was created in V1__init_schema.sql, so an
-- empty database is still provisioned entirely by the migrations.

-- 1536 chosen with the provider: a Gemini "recommended" size, and <= 2000 so an
-- hnsw/ivfflat index stays possible later. Not indexed now: the ward+category+
-- status pre-filter leaves a handful of candidate rows, so brute-force cosine
-- is fine.
ALTER TABLE complaints ADD COLUMN embedding vector(1536);

-- PENDING   — created, not yet processed, or released after a failed run
-- PROCESSING — a backend-node run holds the claim (claim time = updated_at)
-- MATCHED   — the semantic pipeline assigned it (new OR existing incident)
-- DEGRADED  — the naive fallback assigned it; the reconcile job will retry it
ALTER TABLE complaints ADD COLUMN matching_status VARCHAR(16) NOT NULL DEFAULT 'PENDING';
ALTER TABLE complaints ADD COLUMN matched_at TIMESTAMP(6);

-- Anything already grouped was grouped by the naive placeholder, so it is
-- DEGRADED (awaiting semantic reconciliation), not MATCHED. Ungrouped stays
-- PENDING. Both are swept by MatchReconciliationJob once Node is reachable.
UPDATE complaints SET matching_status = 'DEGRADED' WHERE incident_id IS NOT NULL;

-- The reconcile sweep filters on (matching_status, updated_at) — PENDING and
-- DEGRADED always, plus PROCESSING rows older than the stale window. A partial
-- index cannot express "older than now()", so index both columns and let the
-- query predicate do the rest.
CREATE INDEX idx_complaints_matching_status ON complaints (matching_status, updated_at);

-- Every matching decision, for the Phase 8 precision/recall/F1 evaluation:
-- semantic joins and creates, naive fallbacks, and reconcile moves (which are
-- labelled disagreements between the naive baseline and the real pipeline).
CREATE TABLE incident_match_log (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id             BIGINT NOT NULL,
    -- MATCHED (joined existing) | CREATED (started new) | RECONCILED (moved)
    decision                 VARCHAR(16) NOT NULL,
    -- SEMANTIC | NAIVE
    matcher                  VARCHAR(16) NOT NULL,
    chosen_incident_id       BIGINT,
    -- set when a reconcile run moved the complaint off a naive-grouped incident
    previous_incident_id     BIGINT,
    -- the member complaint the score was measured against (single-linkage)
    top_sibling_complaint_id BIGINT,
    top_similarity           DOUBLE PRECISION,
    candidate_count          INTEGER NOT NULL DEFAULT 0,
    threshold                DOUBLE PRECISION,
    model                    VARCHAR(64),
    embedding_dim            INTEGER,
    -- set by Hibernate @CreationTimestamp on insert, like every other table here
    created_at               TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_match_log_complaint
        FOREIGN KEY (complaint_id) REFERENCES complaints (id),
    CONSTRAINT fk_match_log_chosen_incident
        FOREIGN KEY (chosen_incident_id) REFERENCES incidents (id),
    CONSTRAINT fk_match_log_previous_incident
        FOREIGN KEY (previous_incident_id) REFERENCES incidents (id),
    CONSTRAINT fk_match_log_top_sibling
        FOREIGN KEY (top_sibling_complaint_id) REFERENCES complaints (id)
);

CREATE INDEX idx_match_log_complaint  ON incident_match_log (complaint_id);
CREATE INDEX idx_match_log_created_at ON incident_match_log (created_at);
