-- Server-side refresh-token sessions.
--
-- Until now tokens were purely stateless: logout cleared the browser's cookies
-- but the token itself stayed valid for its full 7 days, so a copied refresh
-- token could not be taken away and "sign out everywhere" was impossible.
--
-- Each row is ONE refresh token. Rotation (every /auth/refresh) revokes the
-- presented row as ROTATED and inserts its successor, so a session is a chain
-- of rows sharing one session_id.
--
-- Why the chain is worth storing rather than just the newest token: presenting
-- an already-rotated token is the signature of a stolen one being replayed —
-- the legitimate client would have moved on to the successor. Detecting that
-- lets us revoke the WHOLE session (REUSE_DETECTED) instead of handing an
-- attacker a fresh pair. That is the entire reason rotation is a security
-- control and not just hygiene.
--
-- NOTE ON DEPLOY: refresh tokens issued before this migration carry no `jti`
-- claim and have no row here, so they are rejected on their next refresh.
-- Everyone signed in at deploy time is asked to log in once more. This is a
-- one-off and is the correct fail-closed behaviour.

CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The token's own id (the JWT `jti`). One row per issued refresh token.
    jti            VARCHAR(36) NOT NULL,
    -- Stable across rotations: the login session this chain belongs to. Access
    -- tokens carry it as `sid`, which is what makes them revocable too.
    session_id     VARCHAR(36) NOT NULL,
    user_id        BIGINT NOT NULL,
    issued_at      TIMESTAMP(6) NOT NULL,
    expires_at     TIMESTAMP(6) NOT NULL,
    -- NULL means live. Set on rotation and on every kind of sign-out.
    revoked_at     TIMESTAMP(6),
    -- ROTATED | LOGOUT | LOGOUT_ALL | REUSE_DETECTED
    revoked_reason VARCHAR(16),
    CONSTRAINT uq_refresh_tokens_jti UNIQUE (jti),
    -- Cascade because a session has no meaning without its user. Unlike the
    -- complaint/incident FKs elsewhere in this schema, these rows are
    -- disposable session state, never history worth keeping.
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Revoking a session touches every row in the chain.
CREATE INDEX idx_refresh_tokens_session ON refresh_tokens (session_id);
-- "Sign out everywhere" and the active-session lookup are per user.
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
-- The hourly cleanup job deletes by expiry.
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
