-- Enable pgvector in the application database.
--
-- The official postgres entrypoint runs every file in
-- /docker-entrypoint-initdb.d ONCE, on first cluster initialization only
-- (i.e. when the civicpulse-pgdata volume is empty). It executes against
-- POSTGRES_DB as POSTGRES_USER.
--
-- IF NOT EXISTS keeps it safe to run again by hand after a reset:
--   docker compose exec postgres psql -U civicpulse -d civicpulse \
--     -c "CREATE EXTENSION IF NOT EXISTS vector;"
CREATE EXTENSION IF NOT EXISTS vector;
